[#--<ul class="pages_nav">--]
    [#--[#if header == "welcome"]--]
      [#--<li [#if nav == "traderNote"] class="on"[/#if]><a href="/traderNote/list.action?queryint=0&flag=1&status=0" [#if nav == "traderNote"]class="on"[/#if]>Trader Note</a></li>--]

      [#--[@showMenu url="/noteTypeTrader/add.action"]--]
        [#--<li [#if nav=="noteTypeTraderAdd"] class="on"[/#if]>--]
            [#--<a href="/noteTypeTrader/add.action"[#if nav=="noteTypeTraderAdd"] class="on"[/#if]>NoteTypeTrader</a>--]
        [#--</li>--]
       [#--[/@showMenu]--]
    [#--[/#if]--]
    [#--[#if header == "merchant"]--]
        [#--[@showMenu url="/merchant/list.action?queryint=0&validChildren=true"  hasChildren="true" urlResourceCode="0101"]--]
        [#--<li[#if nav1 == "merchantList" || nav=="profile"] class="on"[/#if]>--]
            [#--<a href="/merchant/list.action?queryint=0"[#if nav1 == "merchantList"] class="on"[/#if]>Merchant List</a>--]
            [#--[#if nav=="profile"]<i>q</i>--]
                [#--<span>--]
                [#--[@showMenu url="/merchant/updateMerchant/codeValue/edit.action"]--]
                    [#--<a href="/merchant/updateMerchant/${code}/edit.action?code=${code}&queryint=0"[#if model == "profile"] class="on"[/#if]>Basic Info</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/merchant/merchantPayCompanyCurrency.action"]--]
                    [#--<a href="/merchant/merchantPayCompanyCurrency.action?merchantCode=${code}" [#if model == "payCurrency"] class="on" [/#if]>渠道及费用</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/bankAccount/list.action"]--]
                    [#--<a href="/bankAccount/list.action?code=${code}&queryint=0"[#if model == "bankAccount"] class="on"[/#if]>Bank Account</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/paper/list.action"]--]
                    [#--<a href="/paper/list.action?code=${code}&queryint=0"[#if model == "paper"] class="on"[/#if]>Paper</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/address/list.action"]--]
                    [#--<a href="/address/list.action?code=${code}&queryint=0"[#if model == "address"] class="on"[/#if]>Address</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/contact/list.action"]--]
                    [#--<a href="/contact/list.action?code=${code}&queryint=0" [#if model == "contact"] class="on" [/#if]>Contact</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/merchantTransferFee/list.action"]--]
                    [#--<a href="/merchantTransferFee/list.action?code=${code}" [#if model == "transferFee"] class="on" [/#if]>转账服务费用</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/product/list.action"]--]
                    [#--<a href="/product/list.action?code=${code}" [#if model == "product"] class="on" [/#if]>Product List</a>--]
                [#--[/@showMenu]--]
                [#--</span>--]
            [#--[/#if]--]
        [#--</li>--]
        [#--[/@showMenu]--]

        [#--[@showMenu url="/wallet/list.action?queryint=0&isPostBack=false"]--]
        [#--<li[#if nav1 == "walletList"] class="on"[/#if]>--]
            [#--<a href="/wallet/list.action?queryint=0&isPostBack=false"[#if nav == "walletList"] class="on"[/#if]>Wallet List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]

        [#--[@showMenu url="/business/list.action?queryint=0"]--]
        [#--<li[#if nav1 == "business"] class="on"[/#if]>--]
            [#--<a href="/business/list.action?queryint=0&myself=1"[#if nav1 == "business"] class="on"[/#if]>Business List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]
    [#--[/#if]--]
    [#--[#if header == "user"]--]
        [#--[@showMenu url="/staff/list.action?queryint=0"]--]
        [#--<li[#if nav == "traderList" || nav == "traderAuth"] class="on"[/#if]><a href="/staff/list.action?queryint=0" [#if nav == "traderList"]class="on"[/#if]>User List</a>--]
            [#--[#if nav == "traderAuth"]<i>q</i>--]
            [#--<span>--]
                [#--<a class="on" href="#">Auth</a>--]
            [#--</span>--]
            [#--[/#if]--]
        [#--</li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/staff/optionLogList.action?queryint=0"]--]
        [#--<li[#if nav == "userOptionLogList"]class="on"[/#if]><a href="/staff/optionLogList.action?queryint=0" [#if nav == "userOptionLogList"]class="on"[/#if]>Option Log</a></li>--]
        [#--[/@showMenu]--]
    [#--[/#if]--]
[#--    [#if header="product"]--]
        [#----][#----][#--[#if nav == "productList" || nav == "productDetail"]--][#----][#----]


        [#----][#----][#--[/#if]--][#----][#----]

    [#--[/#if]--]
    [#--[#if header == "message"]--]
        [#--[@showMenu url="/message/list.action?queryint=0"]--]
        [#--<li[#if nav == "messageList"] class="on"[/#if]><a href="/message/list.action?queryint=0" [#if nav == "messageList"]class="on"[/#if]>Message List</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/signature/list.action?queryint=0"]--]
        [#--<li[#if nav == "signatureList"] class="on"[/#if]><a href="/signature/list.action?queryint=0" [#if nav == "signatureList"]class="on"[/#if]>Signature List</a></li>--]
        [#--[/@showMenu]--]
    [#--[/#if]--]
    [#--[#if header == "setting"]--]
        [#--[@showMenu url="/paycompanyInfo/list.action?queryint=0"]--]
        [#--<li[#if nav == "paycompanyInfoList"] class="on"[/#if]><a href="/paycompanyInfo/list.action?queryint=0" [#if nav == "paycompanyInfoList"]class="on"[/#if]>渠道及费用</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/staff/editPassword.action"]--]
        [#--<li[#if nav == "traderUpdatePassword"] class="on"[/#if]><a href="/staff/editPassword.action" [#if nav == "traderUpdatePassword"]class="on"[/#if]>UpdatePassword</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/merchantExchange/list.action"]--]
        [#--<li[#if nav == "merchantExchangeList"] class="on"[/#if]><a href="/merchantExchange/list.action" [#if nav=="merchantExchangeList"]class="on"[/#if]>MerchantExchange</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/transferFee/list.action"]--]
        [#--<li[#if nav == "transferFeeList"] class="on"[/#if]><a href="/transferFee/list.action" [#if nav=="transferFeeList"]class="on"[/#if]>转账服务费用</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/configuration/list.action?queryint=0"]--]
        [#--<li[#if nav == "configurationList"] class="on"[/#if]><a href="/configuration/list.action?queryint=0" [#if nav=="configurationList"]class="on"[/#if]>Configuration</a></li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/holidayNz/config.action"]--]
        [#--<li[#if nav == "holidayNzConfig"] class="on"[/#if]><a href="/holidayNz/config.action" [#if nav=="holidayNzConfig"]class="on"[/#if]>Config Holiday(NZ)</a></li>--]
        [#--[/@showMenu]--]
        [#--<li[#if nav == "systemBankList"] class="on"[/#if]><a href="/systemBank/list.action" [#if nav=="systemBankList"]class="on"[/#if]>SystemBank</a></li>--]
        [#--[@showMenu url="/exchangeCatalog/list.action?queryint=0"]--]
            [#--<li[#if nav1 == "exchangeCatalog"] class="on"[/#if]>--]
                [#--<a href="/exchangeCatalog/list.action?queryint=0"[#if nav1 == "exchangeCatalog"] class="on"[/#if]>ExchangeCatalog List</a>--]
            [#--</li>--]
        [#--[/@showMenu]--]
    [#--[/#if]--]
    [#--[#if header == "receiverOrder"]--]
        [#--[@showMenu url="/receiverOrder/list.action?queryint=0"]--]
        [#--<li[#if nav == "ReceiverOrderList"] class="on"[/#if]>--]
            [#--<a href="/receiverOrder/list.action?queryint=0"[#if nav == "ReceiverOrderList"] class="on"[/#if]>ReceiverOrder List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/payOrder/list.action?queryint=0"]--]
        [#--<li[#if nav == "PayOrderList"] class="on"[/#if]>--]
            [#--<a href="/payOrder/list.action?queryint=0"[#if nav == "PayOrderList"] class="on"[/#if]>PayOrder List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/settleOrder/list.action?queryint=0"]--]
        [#--<li[#if nav == "SettleOrderList"] class="on"[/#if]>--]
            [#--<a href="/settleOrder/list.action?queryint=0"[#if nav == "SettleOrderList"] class="on"[/#if]>SettleOrder List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/transferOrder/list.action?queryint=0"]--]
        [#--<li[#if nav == "TransferOrderList"] class="on"[/#if]>--]
            [#--<a href="/transferOrder/list.action?queryint=0"[#if nav == "TransferOrderList"] class="on"[/#if]>TransferOrder List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]
        [#--[@showMenu url="/drawMoney/list.action?queryint=0"]--]
        [#--<li[#if nav == "drawMoneyList"] class="on"[/#if]>--]
            [#--<a href="/drawMoney/list.action?queryint=0"[#if nav == "drawMoneyList"] class="on"[/#if]>Withdrawal List</a>--]
        [#--</li>--]
        [#--[/@showMenu]--]

    [#--[/#if]--]
    [#--[#if header == "bank"]--]
    [#--[@showMenu url="/systemBankAccount/view.action?queryint=0"]--]
        [#--<li[#if nav1 == "systemBankList"] class="on"[/#if]><a href="/systemBankAccount/view.action?queryint=0" [#if nav == "systemBankList"]class="on"[/#if]>System Bank List</a></li>--]
    [#--[/@showMenu]--]
        [#--<li[#if nav1 == "statistics"] class="on"[/#if]>--]
        [#--[@showMenu url="/statistics/settleOrderCount.action?queryint=0&validChildren=true" hasChildren="true"  urlResourceCode="0602"]--]
            [#--<a href="/statistics/settleOrderCount.action?queryint=0" >Statistics</a>--]
        [#--[/@showMenu]--]
            [#--[#if nav=="statistics"]<i>q</i>--]
                [#--<span>--]
                [#--[@showMenu url="/statistics/settleOrderCount.action?queryint=0"]--]
                    [#--<a href="/statistics/settleOrderCount.action?queryint=0" [#if model == "unprocessedSettleOrder"]class="on"[/#if]>UnprocessedSettleOrder</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/statistics/platFromTotalBalance.action?model=platFromTotalBalance"]--]
                    [#--<a href="/statistics/platFromTotalBalance.action?model=platFromTotalBalance" [#if model =="platFromTotalBalance"]class="on"[/#if]>PlatformTotalBalance</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/statistics/platFromSelfBalance.action?model=platFromSelfBalance"]--]
                    [#--<a href="/statistics/platFromSelfBalance.action?model=platFromSelfBalance" [#if model =="platFromSelfBalance"]class="on"[/#if]>PlatformSelfBalance</a>--]
                [#--[/@showMenu]--]
                [#--[@showMenu url="/statistics/merchantBalance.action?model=merchantBalance"]--]
                    [#--<a href="/statistics/merchantBalance.action?model=merchantBalance" [#if model =="merchantBalance"]class="on"[/#if]>MerchantTotalBalance</a>--]
                [#--[/@showMenu]--]
                [#--</span>--]
            [#--[/#if]--]
        [#--</li>--]
    [#--[/#if]--]
    [#--</li>--]
[#--</ul>--]